"use client";

import React, { useState } from "react";
import { FileDown, X, Copy, Check, ShieldCheck } from "lucide-react";

interface ReportExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  testResult: any;
}

export const ReportExportModal: React.FC<ReportExportModalProps> = ({
  isOpen,
  onClose,
  testResult,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !testResult) return null;

  const markdownReport = `### 🛡️ SchemaShift Migration Safety Certificate

> Tested in isolated PostgreSQL container (\`postgres:16-alpine\`) with synthetic scale of ${testResult.rows_affected || 10000} rows.

- **Status**: \`${testResult.status.toUpperCase()}\`
- **Danger Score**: **${testResult.danger_score}/100**
- **Isolated Execution Runtime**: \`${testResult.execution_time_ms}ms\`
- **Table Lock Level**: \`${testResult.locks_detected || "RowExclusiveLock"}\`

#### 📊 Blast Radius Analysis
> ${testResult.blast_radius_sentence}

#### ⚡ Proposed Optimized Rewrite
\`\`\`sql
${testResult.ai_rewrite?.rewritten_sql || "-- No rewrite necessary"}
\`\`\`

#### 🔄 Generated Rollback Script (DOWN)
\`\`\`sql
${testResult.rollback_sql}
\`\`\`

*Report generated by SchemaShift PostgreSQL Terrarium Engine.*`;

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(testResult, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `schemashift-safety-report-${testResult.run_id || "run"}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="glass-card w-full max-w-2xl flex flex-col shadow-2xl rounded-2xl border border-sage-green/40 overflow-hidden bg-sage-mist/95">
        {/* Header */}
        <div className="p-4 border-b border-sage-green/20 flex items-center justify-between bg-white/50">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-sage-green" />
            <h3 className="font-serif text-lg font-bold text-forest-ink">
              PR Migration Safety Certificate Exporter
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-forest-ink/70 hover:bg-sage-green/20 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-5 flex flex-col gap-4">
          <p className="text-xs text-forest-ink/75">
            Attach this pre-formatted Markdown summary directly to your GitHub/GitLab Pull Request descriptions to verify migration safety.
          </p>

          <pre className="font-mono text-xs p-4 bg-[#1e1e1e] text-emerald-400 rounded-xl overflow-x-auto border border-sage-green/30 max-h-64 whitespace-pre-wrap">
            {markdownReport}
          </pre>

          <div className="flex items-center justify-end gap-3 pt-2">
            <button
              onClick={handleDownloadJson}
              className="px-4 py-2 rounded-xl text-xs font-medium bg-white/80 hover:bg-white text-forest-ink border border-sage-green/30 transition-all cursor-pointer"
            >
              Download Raw JSON Report
            </button>

            <button
              onClick={handleCopyMarkdown}
              className="px-5 py-2 rounded-xl text-xs font-medium bg-sage-green text-white hover:bg-forest-light transition-all shadow-sm cursor-pointer inline-flex items-center gap-1.5"
            >
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied to Clipboard!" : "Copy PR Markdown Report"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
