apiVersion: v1
kind: Namespace
metadata:
  name: schemashift
---
apiVersion: v1
kind: Namespace
metadata:
  name: schemashift-sandboxes
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
